### ISSUE TITLE
Having a main Widget that all other Widgets get their data from it

### ISSUE THREAD

**Issue by hmny** [angular-dashboard-framework/angular-dashboard-framework#192]
so I am trying to build a main widget that every other widget links to it as a child. The idea is to change the status of all of widgets by changing some parameter in just 'main widget' (main widget is a part of default model)
![widgets!](http://i.imgur.com/IxhvlQi.jpg)
What would be good approach to do so? The problem is I don't know how to pass a value from a widget to the main page, so it can be accessible by all other widgets.

**Comment by ivan-saorin** [comment]
It's definitely possible. We implemented that in a PoC. There was a main widget representing a datasource and other widget that get the data from this datasource widget.

We implemented the solution with events. But, I have to say, that was not an ideal implementation, due to te fact there is not a clear widget lifecycle implemented in the framework. The workaround was having the widgets be able to introspect the adfModel to search each other.

I hope this can help or encourage a proper implementation in the framework.

**Comment by hmny** [comment]
Can you give me the link to that implementation that you mentioned? One possible (but ugly) way to do this is pointing to main page (say index.html) as `templateUrl` of the main widget, but I'll think about the approach you referred. Thanks.

**Comment by ivan-saorin** [comment]
I'm sorry but I can't as it is not an open source project. We have done it in a internal tool at my company.

**Comment by hmny** [comment]
Oh got it. Thanks anyway.
