### ISSUE TITLE
how to include widgets to dist?

### ISSUE THREAD

**Issue by heenaI** [angular-dashboard-framework/angular-dashboard-framework#258]
After gulp all when I deploy the dist directory to my webserver it gives error adf-news-widget not found. Since this is the first widget that I have I am wondering that all of the widgets are not included in dist. I have read the gulp.js file. Just wondering what would be the best way to add widgets to dist folder should this be under dist/sample? and how dows adf deals with all the widget templates?

**Comment by sdorra** [comment]
The dist folder is only for adf releases. You should never use the build for production deployments. The widgets are not included in the dist folder, because they are only for the demo side. If you want to start a project on top of adf, you should use bower to get the framework and all the widgets you need. Please have a look at [adf-dynamic-example](https://github.com/angular-dashboard-framework/adf-dynamic-example) for a demo.
