### ISSUE TITLE
Material design

### ISSUE THREAD

**Issue by gerardolima** [angular-dashboard-framework/angular-dashboard-framework#271]
Is there any plan to port layout to use the Material Design library [angular-material](https://material.angularjs.org/latest/), instead of bootstrap? or, by other means, would it be viable to port on my own fork?

**Comment by raulgomis** [comment]
hi @gerardolima! I don't think that bootstrap should be moved to material as it is still a widely used framework. Instead, I think you could support both by configuring it in the provider and creating the proper material templates. What do you think?

**Comment by jcvpacheco** [comment]
on the "adf.js" file is injecting 'ui.bootstrap'.
Having both could lead to layout problems.
It's possible to override the templates, but this dependency force to use bootstrap, only because internal default templates, right?

**Comment by gerardolima** [comment]
I think it would be good to let the views (_client-code_) choose their preferred layout library, @raulgomis. As @jcvpacheco said, the current implementation requires bootstrap and mixing other library for layout will surely cause incompatibilities errors.

**Comment by sdorra** [comment]
I think we need a way for supporting multiple ui frameworks, because this is not the first question for another ui framework #145. But supporting multiple ui frameworks sounds like a hard business, but i think it is possible. 

We need something like an abstract module for the ui components, with this we could remove the direct dependency to ui-boostrap from adf. Then we could create a module for each ui framework which implements the abstract module. The adf user must include the adf module and one ui-implementation module.

What do you think?

**Comment by gerardolima** [comment]
It makes sense to me to have the views inject the layout library they prefer. Unfortunately, though, I don't know the codebase well enough yet to assert the complexity of these changes.

**Comment by eppak** [comment]
Is a bit trivial but there are some kind of layouts like this http://bootswatch.com/paper/ that can help to mimic this behaviour with bootstrap
