### ISSUE TITLE
Moving widgets to bottom of column

### ISSUE THREAD

**Issue by tcase360** [angular-dashboard-framework/angular-dashboard-framework#54]
Hello,

I'm working on a project with this framework and it's working very well for my needs, first of all. One of the complaints that I have received though was that when moving a widget, you have to drag it to just above one of the other widgets in order to move columns (or of course the top of the column if it is empty). I am trying to solve this problem but so far to no avail. I will keep working on it, but if anyone has any suggestions or wants to point me in the right direction I would love to hear it. Thanks!

**Comment by GoekhanOezen** [comment]
Hi,

i have the same problem. the reason is i dont use the framework exactly the same way how it is used in the demo. So the demo is working good except top navigation for me but my page dont scroll like you described. a solution is to define the sortable objects scroll parameter with the node i want to scroll over. for me 
var sortable = Sortable.create(el, {
                    group: 'widgets',
                    handle: '.adf-move',
                    ghostClass: 'placeholder',
                    animation: 150,
                    scroll: $('.dashboard-container')[0].parentNode, 
// this is the node i want to scroll over. you should place your node here
                    scrollSensitivity: 55 
// this solves the problem with top navigation. because the end of the scroll area is covered with top 
// navigation. so the list doesnt come to an end. this means no scroll. you should give a value greater 
// than the height of the navigaiton
}

my suggestion is:
- i want to use the framework as it is.
- i want this problem to be solved too
- i dont want to place my own solutions in the framework, because maybe this is no problem for others
Result:
so i would say add this code 

     scroll: model.scrollListClassName ? $(model.scrollListClassName)[0] : true

to the sortable object and this would be the only change which could be used over the "dashboard model". if it is not set, the behaviour would be as usual. The name of the "sortable object parameter" doesnt have to be "scrollListClassName" :-). (node, list, scroll ...)
